[build]
  publish = "."
  functions = "netlify/functions"

  [functions]
    node_bundler = "esbuild"

    [functions.import]
      timeout = 26

[[redirects]]
  from = "/api/partners"
  to = "/.netlify/functions/partners"
  status = 200

  [[redirects]]
    from = "/api/import"
      to = "/.netlify/functions/import"
        status = 200
